script:
  - ./autogen.sh
  - make
  - make check
  - pylint -E blueman

env:
  - PYTHON=python2.7
  - PYTHON=python3.2

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq automake autoconf libglib2.0-dev libtool libgtk-3-dev libstartup-notification0-dev python-gi-dev libbluetooth-dev intltool python-dev python3-dev cython python-dbus python3-dbus dh-autoreconf gir1.2-gtk-3.0 gir1.2-gdkpixbuf-2.0 gir1.2-glib-2.0 gir1.2-appindicator3-0.1
  - sudo pip install pylint
